---
deployment:
  tasks:
    - export DEPLOYPATH=/home/toyotai3/public_html/

    # Clean old files
    - /bin/rm -rf $DEPLOYPATH/dist/*

    # Copy public (entry point)
    - /bin/cp -R repositories/toyotailocossur/public/dist/* $DEPLOYPATH/dist/
