services:
  server:
    container_name: ci4
    build:
      context: ./ # The directory to use as build context (current folder)
      target: backend-dev # Dockerfile build stage to target (multi-stage build)
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./app:/var/www/html/app 
      - ./public:/var/www/html/public 
      - ./.env:/var/www/html/.env 
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    ports:
      - 8080:8080 # Map host port 8080 to container port 8080
    command:
      ["php", "spark", "serve", "--host", "0.0.0.0", "--port", "8080"]
      # Run CodeIgniter 4 dev server, accessible from any host
  db:
    platform: linux/x86_64 # Ensure architecture compatibility on MacBook Pro
    image: mysql:8.0.16 # Use MySQL 8.0.16 official image
    container_name: mysql # Name the container "mysql"
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      # Custom SQL mode settings for strict behavior
    ports:
      - 3307:3306 # Map host port 3306 to container port 3306
    environment: # Environment variables for MySQL
      - MYSQL_ROOT_PASSWORD=market # Root password
    volumes:
      - mysql-8.0.16:/var/lib/mysql # Named volume for persistent DB data
volumes:
  mysql-8.0.16: # Declare named volume for MySQL persistence
  vendor: