name: Build and Push to Production

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout main branch
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.14.0

      # 3. Install deps
      - name: Install dependencies
        run: npm install

      # 4. Build Vite
      - name: Build assets
        run: npm run build

      # 5. Prepare deploy folder
      - name: Prepare deploy files
        run: |
          mkdir deploy
          rsync -av --exclude='.git' ./ deploy
          cd deploy
          rm -rf node_modules
          rm -rf .github
          rm -rf resources
          rm -rf Dockerfile
          rm -rf .dockerignore
          rm -rf compose.yml
          rm -rf package.json
          rm -rf package-lock.json
          rm -rf vite.config.js
          rm -rf tsconfig.json

          # Force include dist even if in .gitignore
          echo '!dist' >> .gitignore
          echo '!dist/**' >> .gitignore

      # 6. Push to production branch
      - name: Push to production branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd deploy
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          # Fetch existing production so histories are compatible
          git fetch origin production || true
          git reset --soft origin/production || true

          git checkout -b production
          git add .
          git commit -m "Deploy from main - ${{ github.sha }}"
          git push --force origin production
