name: Build and Push to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout main branch
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24.14.0

      # 3. Install deps
      - name: Install dependencies
        run: npm install

      # 4. Build Vite
      - name: Build assets
        run: npm run build

      # 5. Prepare deploy folder
      - name: Prepare deploy files
        run: |
          mkdir deploy
          rsync -av --exclude='.git' ./ deploy
          cd deploy
          rm -rf node_modules
          rm -rf .github
          rm -rf resources

      # 6. Push to production branch
      - name: Push to production
        run: |
          cd deploy
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b production
          git add .
          git commit -m "Deploy from main"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force origin production
